version: "2"
sql:
  - engine: "postgresql"
    queries: "queries/"
    schema: "migrations"
    gen:
      go:
        package: "trackerdb"
        out: "generated"
        sql_package: "pgx/v5"
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
          - db_type: "pg_catalog.timestamptz"
            go_type: "time.Time"
