[build]
  cmd        = "go build -o ./tmp/server ./cmd/server"
  bin        = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "docs", "internal/infrastructure/generated"]
  delay      = 500

[log]
  time = false
