// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package model

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for IssuePriority.
const (
	High   IssuePriority = "high"
	Low    IssuePriority = "low"
	Medium IssuePriority = "medium"
	None   IssuePriority = "none"
	Urgent IssuePriority = "urgent"
)

// Valid indicates whether the value is a known member of the IssuePriority enum.
func (e IssuePriority) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case None:
		return true
	case Urgent:
		return true
	default:
		return false
	}
}

// Defines values for IssueStatus.
const (
	Backlog    IssueStatus = "backlog"
	Cancelled  IssueStatus = "cancelled"
	Done       IssueStatus = "done"
	InProgress IssueStatus = "in_progress"
	Todo       IssueStatus = "todo"
)

// Valid indicates whether the value is a known member of the IssueStatus enum.
func (e IssueStatus) Valid() bool {
	switch e {
	case Backlog:
		return true
	case Cancelled:
		return true
	case Done:
		return true
	case InProgress:
		return true
	case Todo:
		return true
	default:
		return false
	}
}

// Comment defines model for Comment.
type Comment struct {
	AuthorId  uuid.UUID `json:"authorId"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	Id        uuid.UUID `json:"id"`
	IssueId   uuid.UUID `json:"issueId"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// CommentPage defines model for CommentPage.
type CommentPage struct {
	Items      []Comment `json:"items"`
	NextCursor *string   `json:"nextCursor,omitempty"`
}

// CreateCommentRequest defines model for CreateCommentRequest.
type CreateCommentRequest struct {
	Body string `json:"body"`
}

// CreateIssueRequest defines model for CreateIssueRequest.
type CreateIssueRequest struct {
	AssigneeId  *uuid.UUID    `json:"assigneeId,omitempty"`
	Description *string       `json:"description,omitempty"`
	Priority    IssuePriority `json:"priority"`
	Status      IssueStatus   `json:"status"`
	Title       string        `json:"title"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Issue defines model for Issue.
type Issue struct {
	AssigneeId  *uuid.UUID    `json:"assigneeId,omitempty"`
	CreatedAt   time.Time     `json:"createdAt"`
	Description *string       `json:"description,omitempty"`
	Id          uuid.UUID     `json:"id"`
	Priority    IssuePriority `json:"priority"`
	ProjectId   uuid.UUID     `json:"projectId"`
	ReporterId  uuid.UUID     `json:"reporterId"`
	Status      IssueStatus   `json:"status"`
	Title       string        `json:"title"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

// IssuePage defines model for IssuePage.
type IssuePage struct {
	Items      []Issue `json:"items"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// IssuePriority defines model for IssuePriority.
type IssuePriority string

// IssueStatus defines model for IssueStatus.
type IssueStatus string

// Project defines model for Project.
type Project struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description,omitempty"`
	Id          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	OwnerId     uuid.UUID `json:"ownerId"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// ProjectPage defines model for ProjectPage.
type ProjectPage struct {
	Items      []Project `json:"items"`
	NextCursor *string   `json:"nextCursor,omitempty"`
}

// UpdateCommentRequest defines model for UpdateCommentRequest.
type UpdateCommentRequest struct {
	Body string `json:"body"`
}

// UpdateIssueRequest defines model for UpdateIssueRequest.
type UpdateIssueRequest struct {
	AssigneeId  *uuid.UUID     `json:"assigneeId,omitempty"`
	Description *string        `json:"description,omitempty"`
	Priority    *IssuePriority `json:"priority,omitempty"`
	Status      *IssueStatus   `json:"status,omitempty"`
	Title       *string        `json:"title,omitempty"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"createdAt"`
	Email     string    `json:"email"`
	Id        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// CommentIdParam defines model for CommentIdParam.
type CommentIdParam = uuid.UUID

// CursorParam defines model for CursorParam.
type CursorParam = string

// IssueIdParam defines model for IssueIdParam.
type IssueIdParam = uuid.UUID

// LimitParam defines model for LimitParam.
type LimitParam = int

// ProjectIdParam defines model for ProjectIdParam.
type ProjectIdParam = uuid.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// ListCommentsParams defines parameters for ListComments.
type ListCommentsParams struct {
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListIssuesParams defines parameters for ListIssues.
type ListIssuesParams struct {
	Cursor     *CursorParam   `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit      *LimitParam    `form:"limit,omitempty" json:"limit,omitempty"`
	Status     *IssueStatus   `form:"status,omitempty" json:"status,omitempty"`
	Priority   *IssuePriority `form:"priority,omitempty" json:"priority,omitempty"`
	AssigneeId *uuid.UUID     `form:"assigneeId,omitempty" json:"assigneeId,omitempty"`
}

// UpdateCommentJSONRequestBody defines body for UpdateComment for application/json ContentType.
type UpdateCommentJSONRequestBody = UpdateCommentRequest

// UpdateIssueJSONRequestBody defines body for UpdateIssue for application/json ContentType.
type UpdateIssueJSONRequestBody = UpdateIssueRequest

// CreateCommentJSONRequestBody defines body for CreateComment for application/json ContentType.
type CreateCommentJSONRequestBody = CreateCommentRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// CreateIssueJSONRequestBody defines body for CreateIssue for application/json ContentType.
type CreateIssueJSONRequestBody = CreateIssueRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete a comment.
	// (DELETE /comments/{commentId})
	DeleteComment(ctx echo.Context, commentId CommentIdParam) error
	// Edit the body of a comment.
	// (PATCH /comments/{commentId})
	UpdateComment(ctx echo.Context, commentId CommentIdParam) error
	// Delete an issue and its comments.
	// (DELETE /issues/{issueId})
	DeleteIssue(ctx echo.Context, issueId IssueIdParam) error
	// Get a single issue by ID.
	// (GET /issues/{issueId})
	GetIssue(ctx echo.Context, issueId IssueIdParam) error
	// Partially update an issue (including status transitions).
	// (PATCH /issues/{issueId})
	UpdateIssue(ctx echo.Context, issueId IssueIdParam) error
	// List comments on an issue.
	// (GET /issues/{issueId}/comments)
	ListComments(ctx echo.Context, issueId IssueIdParam, params ListCommentsParams) error
	// Add a comment to an issue.
	// (POST /issues/{issueId}/comments)
	CreateComment(ctx echo.Context, issueId IssueIdParam) error
	// List projects accessible to the authenticated user.
	// (GET /projects)
	ListProjects(ctx echo.Context, params ListProjectsParams) error
	// Create a new project.
	// (POST /projects)
	CreateProject(ctx echo.Context) error
	// Delete a project and all its issues.
	// (DELETE /projects/{projectId})
	DeleteProject(ctx echo.Context, projectId ProjectIdParam) error
	// Get a single project by ID.
	// (GET /projects/{projectId})
	GetProject(ctx echo.Context, projectId ProjectIdParam) error
	// Replace a project's mutable fields.
	// (PUT /projects/{projectId})
	UpdateProject(ctx echo.Context, projectId ProjectIdParam) error
	// List issues in a project with optional filters.
	// (GET /projects/{projectId}/issues)
	ListIssues(ctx echo.Context, projectId ProjectIdParam, params ListIssuesParams) error
	// Create a new issue in a project.
	// (POST /projects/{projectId}/issues)
	CreateIssue(ctx echo.Context, projectId ProjectIdParam) error
	// Get the currently authenticated user.
	// (GET /users/me)
	GetMe(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteComment converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteComment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "commentId" -------------
	var commentId CommentIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "commentId", ctx.Param("commentId"), &commentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter commentId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteComment(ctx, commentId)
	return err
}

// UpdateComment converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateComment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "commentId" -------------
	var commentId CommentIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "commentId", ctx.Param("commentId"), &commentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter commentId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateComment(ctx, commentId)
	return err
}

// DeleteIssue converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteIssue(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteIssue(ctx, issueId)
	return err
}

// GetIssue converts echo context to params.
func (w *ServerInterfaceWrapper) GetIssue(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIssue(ctx, issueId)
	return err
}

// UpdateIssue converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateIssue(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateIssue(ctx, issueId)
	return err
}

// ListComments converts echo context to params.
func (w *ServerInterfaceWrapper) ListComments(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCommentsParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListComments(ctx, issueId, params)
	return err
}

// CreateComment converts echo context to params.
func (w *ServerInterfaceWrapper) CreateComment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateComment(ctx, issueId)
	return err
}

// ListProjects converts echo context to params.
func (w *ServerInterfaceWrapper) ListProjects(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProjects(ctx, params)
	return err
}

// CreateProject converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProject(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProject(ctx)
	return err
}

// DeleteProject converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProject(ctx, projectId)
	return err
}

// GetProject converts echo context to params.
func (w *ServerInterfaceWrapper) GetProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProject(ctx, projectId)
	return err
}

// UpdateProject converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProject(ctx, projectId)
	return err
}

// ListIssues converts echo context to params.
func (w *ServerInterfaceWrapper) ListIssues(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListIssuesParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", ctx.QueryParams(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "priority" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "priority", ctx.QueryParams(), &params.Priority, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter priority: %s", err))
	}

	// ------------- Optional query parameter "assigneeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "assigneeId", ctx.QueryParams(), &params.AssigneeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter assigneeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListIssues(ctx, projectId, params)
	return err
}

// CreateIssue converts echo context to params.
func (w *ServerInterfaceWrapper) CreateIssue(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateIssue(ctx, projectId)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/comments/:commentId", wrapper.DeleteComment)
	router.PATCH(baseURL+"/comments/:commentId", wrapper.UpdateComment)
	router.DELETE(baseURL+"/issues/:issueId", wrapper.DeleteIssue)
	router.GET(baseURL+"/issues/:issueId", wrapper.GetIssue)
	router.PATCH(baseURL+"/issues/:issueId", wrapper.UpdateIssue)
	router.GET(baseURL+"/issues/:issueId/comments", wrapper.ListComments)
	router.POST(baseURL+"/issues/:issueId/comments", wrapper.CreateComment)
	router.GET(baseURL+"/projects", wrapper.ListProjects)
	router.POST(baseURL+"/projects", wrapper.CreateProject)
	router.DELETE(baseURL+"/projects/:projectId", wrapper.DeleteProject)
	router.GET(baseURL+"/projects/:projectId", wrapper.GetProject)
	router.PUT(baseURL+"/projects/:projectId", wrapper.UpdateProject)
	router.GET(baseURL+"/projects/:projectId/issues", wrapper.ListIssues)
	router.POST(baseURL+"/projects/:projectId/issues", wrapper.CreateIssue)
	router.GET(baseURL+"/users/me", wrapper.GetMe)

}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type UnprocessableEntityJSONResponse Error

type DeleteCommentRequestObject struct {
	CommentId CommentIdParam `json:"commentId"`
}

type DeleteCommentResponseObject interface {
	VisitDeleteCommentResponse(w http.ResponseWriter) error
}

type DeleteComment204Response struct {
}

func (response DeleteComment204Response) VisitDeleteCommentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteComment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteComment401JSONResponse) VisitDeleteCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteComment403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteComment403JSONResponse) VisitDeleteCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteComment404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteComment404JSONResponse) VisitDeleteCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteComment500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteComment500JSONResponse) VisitDeleteCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCommentRequestObject struct {
	CommentId CommentIdParam `json:"commentId"`
	Body      *UpdateCommentJSONRequestBody
}

type UpdateCommentResponseObject interface {
	VisitUpdateCommentResponse(w http.ResponseWriter) error
}

type UpdateComment200JSONResponse Comment

func (response UpdateComment200JSONResponse) VisitUpdateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateComment400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateComment400JSONResponse) VisitUpdateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateComment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateComment401JSONResponse) VisitUpdateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateComment403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateComment403JSONResponse) VisitUpdateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateComment404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateComment404JSONResponse) VisitUpdateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateComment500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateComment500JSONResponse) VisitUpdateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteIssueRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
}

type DeleteIssueResponseObject interface {
	VisitDeleteIssueResponse(w http.ResponseWriter) error
}

type DeleteIssue204Response struct {
}

func (response DeleteIssue204Response) VisitDeleteIssueResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteIssue401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteIssue401JSONResponse) VisitDeleteIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteIssue403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteIssue403JSONResponse) VisitDeleteIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteIssue404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteIssue404JSONResponse) VisitDeleteIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteIssue500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteIssue500JSONResponse) VisitDeleteIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetIssueRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
}

type GetIssueResponseObject interface {
	VisitGetIssueResponse(w http.ResponseWriter) error
}

type GetIssue200JSONResponse Issue

func (response GetIssue200JSONResponse) VisitGetIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetIssue401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetIssue401JSONResponse) VisitGetIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetIssue403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetIssue403JSONResponse) VisitGetIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetIssue404JSONResponse struct{ NotFoundJSONResponse }

func (response GetIssue404JSONResponse) VisitGetIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetIssue500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetIssue500JSONResponse) VisitGetIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
	Body    *UpdateIssueJSONRequestBody
}

type UpdateIssueResponseObject interface {
	VisitUpdateIssueResponse(w http.ResponseWriter) error
}

type UpdateIssue200JSONResponse Issue

func (response UpdateIssue200JSONResponse) VisitUpdateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssue400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateIssue400JSONResponse) VisitUpdateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssue401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateIssue401JSONResponse) VisitUpdateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssue403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateIssue403JSONResponse) VisitUpdateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssue404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateIssue404JSONResponse) VisitUpdateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssue422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response UpdateIssue422JSONResponse) VisitUpdateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssue500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateIssue500JSONResponse) VisitUpdateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListCommentsRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
	Params  ListCommentsParams
}

type ListCommentsResponseObject interface {
	VisitListCommentsResponse(w http.ResponseWriter) error
}

type ListComments200JSONResponse CommentPage

func (response ListComments200JSONResponse) VisitListCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListComments401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListComments401JSONResponse) VisitListCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListComments403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListComments403JSONResponse) VisitListCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListComments404JSONResponse struct{ NotFoundJSONResponse }

func (response ListComments404JSONResponse) VisitListCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListComments500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListComments500JSONResponse) VisitListCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateCommentRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
	Body    *CreateCommentJSONRequestBody
}

type CreateCommentResponseObject interface {
	VisitCreateCommentResponse(w http.ResponseWriter) error
}

type CreateComment201JSONResponse Comment

func (response CreateComment201JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateComment400JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateComment401JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateComment403JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateComment404JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateComment422JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateComment500JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListProjectsRequestObject struct {
	Params ListProjectsParams
}

type ListProjectsResponseObject interface {
	VisitListProjectsResponse(w http.ResponseWriter) error
}

type ListProjects200JSONResponse ProjectPage

func (response ListProjects200JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProjects401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListProjects401JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListProjects500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListProjects500JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateProjectRequestObject struct {
	Body *CreateProjectJSONRequestBody
}

type CreateProjectResponseObject interface {
	VisitCreateProjectResponse(w http.ResponseWriter) error
}

type CreateProject201JSONResponse Project

func (response CreateProject201JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateProject400JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateProject401JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateProject422JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateProject500JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProjectRequestObject struct {
	ProjectId ProjectIdParam `json:"projectId"`
}

type DeleteProjectResponseObject interface {
	VisitDeleteProjectResponse(w http.ResponseWriter) error
}

type DeleteProject204Response struct {
}

func (response DeleteProject204Response) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProject401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteProject401JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProject403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteProject403JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProject404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteProject404JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProject500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteProject500JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetProjectRequestObject struct {
	ProjectId ProjectIdParam `json:"projectId"`
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(w http.ResponseWriter) error
}

type GetProject200JSONResponse Project

func (response GetProject200JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProject401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetProject401JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetProject403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetProject403JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetProject404JSONResponse struct{ NotFoundJSONResponse }

func (response GetProject404JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProject500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetProject500JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProjectRequestObject struct {
	ProjectId ProjectIdParam `json:"projectId"`
	Body      *UpdateProjectJSONRequestBody
}

type UpdateProjectResponseObject interface {
	VisitUpdateProjectResponse(w http.ResponseWriter) error
}

type UpdateProject200JSONResponse Project

func (response UpdateProject200JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateProject400JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateProject401JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateProject403JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateProject404JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateProject500JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListIssuesRequestObject struct {
	ProjectId ProjectIdParam `json:"projectId"`
	Params    ListIssuesParams
}

type ListIssuesResponseObject interface {
	VisitListIssuesResponse(w http.ResponseWriter) error
}

type ListIssues200JSONResponse IssuePage

func (response ListIssues200JSONResponse) VisitListIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListIssues401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListIssues401JSONResponse) VisitListIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListIssues403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListIssues403JSONResponse) VisitListIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListIssues404JSONResponse struct{ NotFoundJSONResponse }

func (response ListIssues404JSONResponse) VisitListIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListIssues500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListIssues500JSONResponse) VisitListIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssueRequestObject struct {
	ProjectId ProjectIdParam `json:"projectId"`
	Body      *CreateIssueJSONRequestBody
}

type CreateIssueResponseObject interface {
	VisitCreateIssueResponse(w http.ResponseWriter) error
}

type CreateIssue201JSONResponse Issue

func (response CreateIssue201JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateIssue400JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateIssue401JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateIssue403JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateIssue404JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateIssue422JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateIssue500JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetMe500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetMe500JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Delete a comment.
	// (DELETE /comments/{commentId})
	DeleteComment(ctx context.Context, request DeleteCommentRequestObject) (DeleteCommentResponseObject, error)
	// Edit the body of a comment.
	// (PATCH /comments/{commentId})
	UpdateComment(ctx context.Context, request UpdateCommentRequestObject) (UpdateCommentResponseObject, error)
	// Delete an issue and its comments.
	// (DELETE /issues/{issueId})
	DeleteIssue(ctx context.Context, request DeleteIssueRequestObject) (DeleteIssueResponseObject, error)
	// Get a single issue by ID.
	// (GET /issues/{issueId})
	GetIssue(ctx context.Context, request GetIssueRequestObject) (GetIssueResponseObject, error)
	// Partially update an issue (including status transitions).
	// (PATCH /issues/{issueId})
	UpdateIssue(ctx context.Context, request UpdateIssueRequestObject) (UpdateIssueResponseObject, error)
	// List comments on an issue.
	// (GET /issues/{issueId}/comments)
	ListComments(ctx context.Context, request ListCommentsRequestObject) (ListCommentsResponseObject, error)
	// Add a comment to an issue.
	// (POST /issues/{issueId}/comments)
	CreateComment(ctx context.Context, request CreateCommentRequestObject) (CreateCommentResponseObject, error)
	// List projects accessible to the authenticated user.
	// (GET /projects)
	ListProjects(ctx context.Context, request ListProjectsRequestObject) (ListProjectsResponseObject, error)
	// Create a new project.
	// (POST /projects)
	CreateProject(ctx context.Context, request CreateProjectRequestObject) (CreateProjectResponseObject, error)
	// Delete a project and all its issues.
	// (DELETE /projects/{projectId})
	DeleteProject(ctx context.Context, request DeleteProjectRequestObject) (DeleteProjectResponseObject, error)
	// Get a single project by ID.
	// (GET /projects/{projectId})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// Replace a project's mutable fields.
	// (PUT /projects/{projectId})
	UpdateProject(ctx context.Context, request UpdateProjectRequestObject) (UpdateProjectResponseObject, error)
	// List issues in a project with optional filters.
	// (GET /projects/{projectId}/issues)
	ListIssues(ctx context.Context, request ListIssuesRequestObject) (ListIssuesResponseObject, error)
	// Create a new issue in a project.
	// (POST /projects/{projectId}/issues)
	CreateIssue(ctx context.Context, request CreateIssueRequestObject) (CreateIssueResponseObject, error)
	// Get the currently authenticated user.
	// (GET /users/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// DeleteComment operation middleware
func (sh *strictHandler) DeleteComment(ctx echo.Context, commentId CommentIdParam) error {
	var request DeleteCommentRequestObject

	request.CommentId = commentId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteComment(ctx.Request().Context(), request.(DeleteCommentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteComment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteCommentResponseObject); ok {
		return validResponse.VisitDeleteCommentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateComment operation middleware
func (sh *strictHandler) UpdateComment(ctx echo.Context, commentId CommentIdParam) error {
	var request UpdateCommentRequestObject

	request.CommentId = commentId

	var body UpdateCommentJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateComment(ctx.Request().Context(), request.(UpdateCommentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateComment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateCommentResponseObject); ok {
		return validResponse.VisitUpdateCommentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteIssue operation middleware
func (sh *strictHandler) DeleteIssue(ctx echo.Context, issueId IssueIdParam) error {
	var request DeleteIssueRequestObject

	request.IssueId = issueId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteIssue(ctx.Request().Context(), request.(DeleteIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteIssue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteIssueResponseObject); ok {
		return validResponse.VisitDeleteIssueResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetIssue operation middleware
func (sh *strictHandler) GetIssue(ctx echo.Context, issueId IssueIdParam) error {
	var request GetIssueRequestObject

	request.IssueId = issueId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetIssue(ctx.Request().Context(), request.(GetIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIssue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetIssueResponseObject); ok {
		return validResponse.VisitGetIssueResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateIssue operation middleware
func (sh *strictHandler) UpdateIssue(ctx echo.Context, issueId IssueIdParam) error {
	var request UpdateIssueRequestObject

	request.IssueId = issueId

	var body UpdateIssueJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateIssue(ctx.Request().Context(), request.(UpdateIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateIssue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateIssueResponseObject); ok {
		return validResponse.VisitUpdateIssueResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListComments operation middleware
func (sh *strictHandler) ListComments(ctx echo.Context, issueId IssueIdParam, params ListCommentsParams) error {
	var request ListCommentsRequestObject

	request.IssueId = issueId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListComments(ctx.Request().Context(), request.(ListCommentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListComments")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListCommentsResponseObject); ok {
		return validResponse.VisitListCommentsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateComment operation middleware
func (sh *strictHandler) CreateComment(ctx echo.Context, issueId IssueIdParam) error {
	var request CreateCommentRequestObject

	request.IssueId = issueId

	var body CreateCommentJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateComment(ctx.Request().Context(), request.(CreateCommentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateComment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateCommentResponseObject); ok {
		return validResponse.VisitCreateCommentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListProjects operation middleware
func (sh *strictHandler) ListProjects(ctx echo.Context, params ListProjectsParams) error {
	var request ListProjectsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjects(ctx.Request().Context(), request.(ListProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjects")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListProjectsResponseObject); ok {
		return validResponse.VisitListProjectsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateProject operation middleware
func (sh *strictHandler) CreateProject(ctx echo.Context) error {
	var request CreateProjectRequestObject

	var body CreateProjectJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProject(ctx.Request().Context(), request.(CreateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateProjectResponseObject); ok {
		return validResponse.VisitCreateProjectResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteProject operation middleware
func (sh *strictHandler) DeleteProject(ctx echo.Context, projectId ProjectIdParam) error {
	var request DeleteProjectRequestObject

	request.ProjectId = projectId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProject(ctx.Request().Context(), request.(DeleteProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteProjectResponseObject); ok {
		return validResponse.VisitDeleteProjectResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(ctx echo.Context, projectId ProjectIdParam) error {
	var request GetProjectRequestObject

	request.ProjectId = projectId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx.Request().Context(), request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		return validResponse.VisitGetProjectResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateProject operation middleware
func (sh *strictHandler) UpdateProject(ctx echo.Context, projectId ProjectIdParam) error {
	var request UpdateProjectRequestObject

	request.ProjectId = projectId

	var body UpdateProjectJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProject(ctx.Request().Context(), request.(UpdateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateProjectResponseObject); ok {
		return validResponse.VisitUpdateProjectResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListIssues operation middleware
func (sh *strictHandler) ListIssues(ctx echo.Context, projectId ProjectIdParam, params ListIssuesParams) error {
	var request ListIssuesRequestObject

	request.ProjectId = projectId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListIssues(ctx.Request().Context(), request.(ListIssuesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListIssues")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListIssuesResponseObject); ok {
		return validResponse.VisitListIssuesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateIssue operation middleware
func (sh *strictHandler) CreateIssue(ctx echo.Context, projectId ProjectIdParam) error {
	var request CreateIssueRequestObject

	request.ProjectId = projectId

	var body CreateIssueJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateIssue(ctx.Request().Context(), request.(CreateIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateIssue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateIssueResponseObject); ok {
		return validResponse.VisitCreateIssueResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx echo.Context) error {
	var request GetMeRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.Request().Context(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		return validResponse.VisitGetMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbW2/bNhT+KwQ3YBugWE6avfgtbdPCQzsYSYM9BMFAS8cyG4pUSSqJF+i/DyR1jSVf",
	"CtkOkrzFCkUenvOd71xIPeJAxIngwLXCo0ecEEli0CDtrw8ijoHrcTgxj80TyvEIJ0TPsYc5iQGPzARu",
	"EPawhB8plRDikZYpeFgFc4iJeXEmZEw0HuE0pWakXiTmZaUl5RH28MNRJI7yh2bI4Opq/LH+/IjGiZDa",
	"CanneIQjqufpdBCI2I+EiBj4du4syzz8IZVKyKbYP1KQi5rcdgiuC9kUyswzViqF1funbshz2v0XGlO9",
	"cvPMjGjsPYQZSZnGo5Ohh2PyQOM0xqPjoflFef6rlJxyDRFIq6OJFN8hWIOSpBj0fPSUGUlUIrgCi/b3",
	"JLyAHyko+3oguAZu/yRJwmhANBXc/64EN88qmX+VMMMj/ItfeZLv/qv8cymFdDYJQQWSJmYSPMJjfkcY",
	"DZF0C6KELJggIRISVS44wJmHPwk5pWEIfPdCnaV6DlybWSFEqQKJGAluFUpAxlQpKrgVacw1SE7YJcg7",
	"kG66nQt3xeEhgcBIpuy6CMxQK9DfQn8SKQ93L8UFKJHKABAXGs3MmlaAK05SPReS/gd7EOKrsQWPDFho",
	"jiNSmY4KjrS4BZ5LlkgRgFJkyuCca6oXuxfwEmJihEFWOCdSYa2s8Pd6hLH+KkUCUlPnjE6f43DfrODh",
	"qQgXLcHAw4EE4xhnuiFTSDQcaRrDkmCZh+kB5C/i0d4XTpNwO/1k9VBwja2IVTQtEZCbpG6A+mI35bxi",
	"akKM0XsOqwmJYBlaVEPc/GMVyAuEZuUyREqyML85PGiXaJhJeMqYcbIiqq3ZrF27VXa7y3zZWkBqbqJA",
	"aUz5F+CRsc3xujXtO91L2lync0GiFI04dCBr9eb7RlqDbdZq3sOJpELmzLfK1lYDk2KwYSpNdKo2eu3S",
	"DTUwoZpBezpZt4YbVq5Rk7LbRHmq1WmkbRXjkrN1ktpRbUKVob8pRSBCaGXQ2MShaIMV7QzV+La1rdKf",
	"N0x/ImBsa8BDBJif9qaqBti7zBLMWDhIQtErifQUZuvlWDcRNfS2Tfx1pu8h+jov31vsbUJ29IiBm7r3",
	"GnPBjYpSGZlcwMNzGs0tQYU0jbGHmbivTVgZq27V2nRTEtwyYaCmRShM2sP/TaSIJChjgNCtFhAeAGMQ",
	"tk6dx4IW+n2ZtNMRqzws7vlhHLsXT7TbqjaxjZflCOjDzwow7c3TruzO9prluiXfstydZ7kdmn9myeuV",
	"AtkLeUJMKGsMd09W4+OZkmkvnFbsP+e2TRnNQBGC1MDy0oAu5wAgEuRZarZU/PpUCPbXP9+KLraZyf23",
	"EnKudeIaVJTPxBLI8MX55Td0NhmjmZBIzwHZ9gPSkgS3IFGtNTYoE6WRC+roWz7obDLGHr4Dqdycx4Ph",
	"YGjjUgKcJBSP8LvBcPDOJFZEz+2e/PzQRPmP5fFJ5sRjoK1lDCjtyoaK8Ef7vOhFPGlcnwxPl7eWj0Vu",
	"RtemPB0ed3l5OaHf6GXal96tf6nqUts3Tte/UfZsMw//ORyuf6Gt62whk8YxkYtSSYigXKfWZiRSrqJ0",
	"Csc3hilrp1zX7etWQ/wnp2DZjTVkMF+2UiOo5QcdoPT7PIr10nRtDZxZ0w0NYWZLIBn2JkPZE2tp0zv/",
	"rkxg8bCBeWunLy8fqech1ZZvTLKCxGwtZjMP+5ablP+Yt0g34AtXPW3CFo7SXiFX8JzyCQ8R1aowg6rb",
	"wSneMkcEelnZn0F3aLo/l8sL4ZaTxNxymlCmXoPlPoNGBCnKI1bE6+kCjT92WGw7rm+c969l+srqu+L5",
	"RrWyZ5bvhFzB8VbLL43hT09ONpFr+VS1P4RPiNSUMLZALluuWOp3ygOWhpRHyBVtJlXlihrDqD9aPaAt",
	"cpTpp5G2ldK+UKU/FIO2Tphql28yb+3w2m0V43G7zlpsu6QF1RMSUW5xzajSJihXseDls6oxeLlhJHiJ",
	"uZ6S6GViFaoFd43Dzx0xa+sB60bceryPDLoo3PKq+Y1fe+fXszCsEm6kxTqsGwrND0xWM+akGPRCGLPe",
	"YN6IMQst/Txj9klnhTSIBAZLdMrAWNvUXWTpqlvd9qWxLc+tIKqibb5LonrSNt0zUZUHAy3md/86DFEd",
	"nkWcdRBBHO4LqHWAqE4g/mN59rpBBV8H2LoavrDHa+z45Tq1ZTxhzJbyLuvt9OuuUr5T5cN9OtVrLegL",
	"Qy6V9E1O3iq6PrmgbrPPVHcV9bvl9NajsD0X9ivgV5T2JZ+9tW9bEHsBCSNBjXd+UyhOtQkzaEaBhWrL",
	"QJBX6CuTy7EbssfU0mv/dqS8J7RFG6k4N+6as3blaItZq0Psrnlr5/kH+87kZtc9us3z8yIkvpJ+htsu",
	"oryWIdxTPUfCqogwNKPMfWnTQ++4LcysqB122TxuudC957phzXnFW3NjL2WJ6xrX8d/ZIzY1sPLdrZCu",
	"1PjrTo+47IWctoZYKiVw7T5IS6SYUQYHbzCYpFXPAQVOOLZY01Kw6jWqrl1ysaRSv95yfWNIw33e5ign",
	"lQyPsE8S6t8d4+wm+z8AAP//zFKeWbE7AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
