// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package model

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for IssuePriority.
const (
	High   IssuePriority = "high"
	Low    IssuePriority = "low"
	Medium IssuePriority = "medium"
	None   IssuePriority = "none"
	Urgent IssuePriority = "urgent"
)

// Valid indicates whether the value is a known member of the IssuePriority enum.
func (e IssuePriority) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case None:
		return true
	case Urgent:
		return true
	default:
		return false
	}
}

// Defines values for IssueStatus.
const (
	Backlog    IssueStatus = "backlog"
	Cancelled  IssueStatus = "cancelled"
	Done       IssueStatus = "done"
	InProgress IssueStatus = "in_progress"
	Todo       IssueStatus = "todo"
)

// Valid indicates whether the value is a known member of the IssueStatus enum.
func (e IssueStatus) Valid() bool {
	switch e {
	case Backlog:
		return true
	case Cancelled:
		return true
	case Done:
		return true
	case InProgress:
		return true
	case Todo:
		return true
	default:
		return false
	}
}

// Comment defines model for Comment.
type Comment struct {
	AuthorId  uuid.UUID `json:"authorId"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	Id        uuid.UUID `json:"id"`
	IssueId   uuid.UUID `json:"issueId"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// CommentPage defines model for CommentPage.
type CommentPage struct {
	Items      []Comment `json:"items"`
	NextCursor *string   `json:"nextCursor,omitempty"`
}

// CreateCommentRequest defines model for CreateCommentRequest.
type CreateCommentRequest struct {
	Body string `json:"body"`
}

// CreateIssueRequest defines model for CreateIssueRequest.
type CreateIssueRequest struct {
	AssigneeId  *uuid.UUID    `json:"assigneeId,omitempty"`
	Description *string       `json:"description,omitempty"`
	Priority    IssuePriority `json:"priority"`
	ProjectId   uuid.UUID     `json:"projectId"`
	Status      IssueStatus   `json:"status"`
	Title       string        `json:"title"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Issue defines model for Issue.
type Issue struct {
	AssigneeId  *uuid.UUID    `json:"assigneeId,omitempty"`
	CreatedAt   time.Time     `json:"createdAt"`
	Description *string       `json:"description,omitempty"`
	Id          uuid.UUID     `json:"id"`
	Identifier  string        `json:"identifier"`
	Labels      []string      `json:"labels"`
	Priority    IssuePriority `json:"priority"`
	ProjectId   uuid.UUID     `json:"projectId"`
	ReporterId  uuid.UUID     `json:"reporterId"`
	Status      IssueStatus   `json:"status"`
	Title       string        `json:"title"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

// IssuePage defines model for IssuePage.
type IssuePage struct {
	Items      []Issue `json:"items"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// IssuePriority defines model for IssuePriority.
type IssuePriority string

// IssueStatus defines model for IssueStatus.
type IssueStatus string

// Project defines model for Project.
type Project struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description,omitempty"`
	Id          uuid.UUID `json:"id"`
	Identifier  string    `json:"identifier"`
	IssueCount  int       `json:"issueCount"`
	Name        string    `json:"name"`
	OwnerId     uuid.UUID `json:"ownerId"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// ProjectPage defines model for ProjectPage.
type ProjectPage struct {
	Items      []Project `json:"items"`
	NextCursor *string   `json:"nextCursor,omitempty"`
}

// SearchIssueRequest defines model for SearchIssueRequest.
type SearchIssueRequest struct {
	Query string `json:"query"`
}

// UpdateIssueAssigneeRequest defines model for UpdateIssueAssigneeRequest.
type UpdateIssueAssigneeRequest struct {
	AssigneeId *uuid.UUID `json:"assigneeId"`
}

// UpdateIssueDescriptionRequest defines model for UpdateIssueDescriptionRequest.
type UpdateIssueDescriptionRequest struct {
	Description *string `json:"description"`
}

// UpdateIssuePriorityRequest defines model for UpdateIssuePriorityRequest.
type UpdateIssuePriorityRequest struct {
	Priority IssuePriority `json:"priority"`
}

// UpdateIssueStatusRequest defines model for UpdateIssueStatusRequest.
type UpdateIssueStatusRequest struct {
	Status IssueStatus `json:"status"`
}

// UpdateIssueTitleRequest defines model for UpdateIssueTitleRequest.
type UpdateIssueTitleRequest struct {
	Title string `json:"title"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"createdAt"`
	Email     string    `json:"email"`
	Id        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// CommentIdParam defines model for CommentIdParam.
type CommentIdParam = uuid.UUID

// CursorParam defines model for CursorParam.
type CursorParam = string

// IssueIdParam defines model for IssueIdParam.
type IssueIdParam = uuid.UUID

// LimitParam defines model for LimitParam.
type LimitParam = int

// ProjectIdParam defines model for ProjectIdParam.
type ProjectIdParam = uuid.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// NotImplemented defines model for NotImplemented.
type NotImplemented = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// ListIssuesParams defines parameters for ListIssues.
type ListIssuesParams struct {
	ProjectId  uuid.UUID      `form:"project_id" json:"project_id"`
	Cursor     *CursorParam   `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit      *LimitParam    `form:"limit,omitempty" json:"limit,omitempty"`
	Status     *IssueStatus   `form:"status,omitempty" json:"status,omitempty"`
	Priority   *IssuePriority `form:"priority,omitempty" json:"priority,omitempty"`
	AssigneeId *uuid.UUID     `form:"assigneeId,omitempty" json:"assigneeId,omitempty"`
}

// ListCommentsParams defines parameters for ListComments.
type ListCommentsParams struct {
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	Cursor *CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *LimitParam  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateIssueJSONRequestBody defines body for CreateIssue for application/json ContentType.
type CreateIssueJSONRequestBody = CreateIssueRequest

// SearchIssuesJSONRequestBody defines body for SearchIssues for application/json ContentType.
type SearchIssuesJSONRequestBody = SearchIssueRequest

// UpdateIssueAssigneeJSONRequestBody defines body for UpdateIssueAssignee for application/json ContentType.
type UpdateIssueAssigneeJSONRequestBody = UpdateIssueAssigneeRequest

// CreateCommentJSONRequestBody defines body for CreateComment for application/json ContentType.
type CreateCommentJSONRequestBody = CreateCommentRequest

// UpdateIssueDescriptionJSONRequestBody defines body for UpdateIssueDescription for application/json ContentType.
type UpdateIssueDescriptionJSONRequestBody = UpdateIssueDescriptionRequest

// UpdateIssuePriorityJSONRequestBody defines body for UpdateIssuePriority for application/json ContentType.
type UpdateIssuePriorityJSONRequestBody = UpdateIssuePriorityRequest

// UpdateIssueStatusJSONRequestBody defines body for UpdateIssueStatus for application/json ContentType.
type UpdateIssueStatusJSONRequestBody = UpdateIssueStatusRequest

// UpdateIssueTitleJSONRequestBody defines body for UpdateIssueTitle for application/json ContentType.
type UpdateIssueTitleJSONRequestBody = UpdateIssueTitleRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete a comment.
	// (DELETE /comments/{commentId})
	DeleteComment(ctx echo.Context, commentId CommentIdParam) error
	// List issues with optional filters.
	// (GET /issues)
	ListIssues(ctx echo.Context, params ListIssuesParams) error
	// Create a new issue.
	// (POST /issues)
	CreateIssue(ctx echo.Context) error
	// Search issues by a query string.
	// (POST /issues/search)
	SearchIssues(ctx echo.Context) error
	// Delete an issue and its comments.
	// (DELETE /issues/{issueId})
	DeleteIssue(ctx echo.Context, issueId IssueIdParam) error
	// Get a single issue by ID.
	// (GET /issues/{issueId})
	GetIssue(ctx echo.Context, issueId IssueIdParam) error
	// Update the assignee of an issue.
	// (PUT /issues/{issueId}/assigneeId)
	UpdateIssueAssignee(ctx echo.Context, issueId IssueIdParam) error
	// List comments on an issue.
	// (GET /issues/{issueId}/comments)
	ListComments(ctx echo.Context, issueId IssueIdParam, params ListCommentsParams) error
	// Add a comment to an issue.
	// (POST /issues/{issueId}/comments)
	CreateComment(ctx echo.Context, issueId IssueIdParam) error
	// Update the description of an issue.
	// (PUT /issues/{issueId}/description)
	UpdateIssueDescription(ctx echo.Context, issueId IssueIdParam) error
	// Update the priority of an issue.
	// (PUT /issues/{issueId}/priority)
	UpdateIssuePriority(ctx echo.Context, issueId IssueIdParam) error
	// Update the status of an issue.
	// (PUT /issues/{issueId}/status)
	UpdateIssueStatus(ctx echo.Context, issueId IssueIdParam) error
	// Update the title of an issue.
	// (PUT /issues/{issueId}/title)
	UpdateIssueTitle(ctx echo.Context, issueId IssueIdParam) error
	// List projects accessible to the authenticated user.
	// (GET /projects)
	ListProjects(ctx echo.Context, params ListProjectsParams) error
	// Create a new project.
	// (POST /projects)
	CreateProject(ctx echo.Context) error
	// Delete a project and all its issues.
	// (DELETE /projects/{projectId})
	DeleteProject(ctx echo.Context, projectId ProjectIdParam) error
	// Get a single project by ID.
	// (GET /projects/{projectId})
	GetProject(ctx echo.Context, projectId ProjectIdParam) error
	// Replace a project's mutable fields.
	// (PUT /projects/{projectId})
	UpdateProject(ctx echo.Context, projectId ProjectIdParam) error
	// Get the currently authenticated user.
	// (GET /users/me)
	GetMe(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteComment converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteComment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "commentId" -------------
	var commentId CommentIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "commentId", ctx.Param("commentId"), &commentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter commentId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteComment(ctx, commentId)
	return err
}

// ListIssues converts echo context to params.
func (w *ServerInterfaceWrapper) ListIssues(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListIssuesParams
	// ------------- Required query parameter "project_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "project_id", ctx.QueryParams(), &params.ProjectId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter project_id: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", ctx.QueryParams(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "priority" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "priority", ctx.QueryParams(), &params.Priority, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter priority: %s", err))
	}

	// ------------- Optional query parameter "assigneeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "assigneeId", ctx.QueryParams(), &params.AssigneeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter assigneeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListIssues(ctx, params)
	return err
}

// CreateIssue converts echo context to params.
func (w *ServerInterfaceWrapper) CreateIssue(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateIssue(ctx)
	return err
}

// SearchIssues converts echo context to params.
func (w *ServerInterfaceWrapper) SearchIssues(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchIssues(ctx)
	return err
}

// DeleteIssue converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteIssue(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteIssue(ctx, issueId)
	return err
}

// GetIssue converts echo context to params.
func (w *ServerInterfaceWrapper) GetIssue(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIssue(ctx, issueId)
	return err
}

// UpdateIssueAssignee converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateIssueAssignee(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateIssueAssignee(ctx, issueId)
	return err
}

// ListComments converts echo context to params.
func (w *ServerInterfaceWrapper) ListComments(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCommentsParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListComments(ctx, issueId, params)
	return err
}

// CreateComment converts echo context to params.
func (w *ServerInterfaceWrapper) CreateComment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateComment(ctx, issueId)
	return err
}

// UpdateIssueDescription converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateIssueDescription(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateIssueDescription(ctx, issueId)
	return err
}

// UpdateIssuePriority converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateIssuePriority(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateIssuePriority(ctx, issueId)
	return err
}

// UpdateIssueStatus converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateIssueStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateIssueStatus(ctx, issueId)
	return err
}

// UpdateIssueTitle converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateIssueTitle(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "issueId" -------------
	var issueId IssueIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "issueId", ctx.Param("issueId"), &issueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter issueId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateIssueTitle(ctx, issueId)
	return err
}

// ListProjects converts echo context to params.
func (w *ServerInterfaceWrapper) ListProjects(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProjects(ctx, params)
	return err
}

// CreateProject converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProject(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProject(ctx)
	return err
}

// DeleteProject converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProject(ctx, projectId)
	return err
}

// GetProject converts echo context to params.
func (w *ServerInterfaceWrapper) GetProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProject(ctx, projectId)
	return err
}

// UpdateProject converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProject(ctx, projectId)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/comments/:commentId", wrapper.DeleteComment)
	router.GET(baseURL+"/issues", wrapper.ListIssues)
	router.POST(baseURL+"/issues", wrapper.CreateIssue)
	router.POST(baseURL+"/issues/search", wrapper.SearchIssues)
	router.DELETE(baseURL+"/issues/:issueId", wrapper.DeleteIssue)
	router.GET(baseURL+"/issues/:issueId", wrapper.GetIssue)
	router.PUT(baseURL+"/issues/:issueId/assigneeId", wrapper.UpdateIssueAssignee)
	router.GET(baseURL+"/issues/:issueId/comments", wrapper.ListComments)
	router.POST(baseURL+"/issues/:issueId/comments", wrapper.CreateComment)
	router.PUT(baseURL+"/issues/:issueId/description", wrapper.UpdateIssueDescription)
	router.PUT(baseURL+"/issues/:issueId/priority", wrapper.UpdateIssuePriority)
	router.PUT(baseURL+"/issues/:issueId/status", wrapper.UpdateIssueStatus)
	router.PUT(baseURL+"/issues/:issueId/title", wrapper.UpdateIssueTitle)
	router.GET(baseURL+"/projects", wrapper.ListProjects)
	router.POST(baseURL+"/projects", wrapper.CreateProject)
	router.DELETE(baseURL+"/projects/:projectId", wrapper.DeleteProject)
	router.GET(baseURL+"/projects/:projectId", wrapper.GetProject)
	router.PUT(baseURL+"/projects/:projectId", wrapper.UpdateProject)
	router.GET(baseURL+"/users/me", wrapper.GetMe)

}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type NotImplementedJSONResponse Error

type UnauthorizedJSONResponse Error

type UnprocessableEntityJSONResponse Error

type DeleteCommentRequestObject struct {
	CommentId CommentIdParam `json:"commentId"`
}

type DeleteCommentResponseObject interface {
	VisitDeleteCommentResponse(w http.ResponseWriter) error
}

type DeleteComment204Response struct {
}

func (response DeleteComment204Response) VisitDeleteCommentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteComment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteComment401JSONResponse) VisitDeleteCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteComment403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteComment403JSONResponse) VisitDeleteCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteComment404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteComment404JSONResponse) VisitDeleteCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteComment500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteComment500JSONResponse) VisitDeleteCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListIssuesRequestObject struct {
	Params ListIssuesParams
}

type ListIssuesResponseObject interface {
	VisitListIssuesResponse(w http.ResponseWriter) error
}

type ListIssues200JSONResponse IssuePage

func (response ListIssues200JSONResponse) VisitListIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListIssues401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListIssues401JSONResponse) VisitListIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListIssues404JSONResponse struct{ NotFoundJSONResponse }

func (response ListIssues404JSONResponse) VisitListIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListIssues500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListIssues500JSONResponse) VisitListIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssueRequestObject struct {
	Body *CreateIssueJSONRequestBody
}

type CreateIssueResponseObject interface {
	VisitCreateIssueResponse(w http.ResponseWriter) error
}

type CreateIssue201JSONResponse Issue

func (response CreateIssue201JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateIssue400JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateIssue401JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateIssue404JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateIssue422JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateIssue500JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SearchIssuesRequestObject struct {
	Body *SearchIssuesJSONRequestBody
}

type SearchIssuesResponseObject interface {
	VisitSearchIssuesResponse(w http.ResponseWriter) error
}

type SearchIssues400JSONResponse struct{ BadRequestJSONResponse }

func (response SearchIssues400JSONResponse) VisitSearchIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SearchIssues501JSONResponse struct{ NotImplementedJSONResponse }

func (response SearchIssues501JSONResponse) VisitSearchIssuesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type DeleteIssueRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
}

type DeleteIssueResponseObject interface {
	VisitDeleteIssueResponse(w http.ResponseWriter) error
}

type DeleteIssue204Response struct {
}

func (response DeleteIssue204Response) VisitDeleteIssueResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteIssue401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteIssue401JSONResponse) VisitDeleteIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteIssue403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteIssue403JSONResponse) VisitDeleteIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteIssue404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteIssue404JSONResponse) VisitDeleteIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteIssue500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteIssue500JSONResponse) VisitDeleteIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetIssueRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
}

type GetIssueResponseObject interface {
	VisitGetIssueResponse(w http.ResponseWriter) error
}

type GetIssue200JSONResponse Issue

func (response GetIssue200JSONResponse) VisitGetIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetIssue401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetIssue401JSONResponse) VisitGetIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetIssue403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetIssue403JSONResponse) VisitGetIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetIssue404JSONResponse struct{ NotFoundJSONResponse }

func (response GetIssue404JSONResponse) VisitGetIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetIssue500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetIssue500JSONResponse) VisitGetIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueAssigneeRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
	Body    *UpdateIssueAssigneeJSONRequestBody
}

type UpdateIssueAssigneeResponseObject interface {
	VisitUpdateIssueAssigneeResponse(w http.ResponseWriter) error
}

type UpdateIssueAssignee200JSONResponse Issue

func (response UpdateIssueAssignee200JSONResponse) VisitUpdateIssueAssigneeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueAssignee400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateIssueAssignee400JSONResponse) VisitUpdateIssueAssigneeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueAssignee401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateIssueAssignee401JSONResponse) VisitUpdateIssueAssigneeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueAssignee403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateIssueAssignee403JSONResponse) VisitUpdateIssueAssigneeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueAssignee404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateIssueAssignee404JSONResponse) VisitUpdateIssueAssigneeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueAssignee500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateIssueAssignee500JSONResponse) VisitUpdateIssueAssigneeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueAssignee501JSONResponse struct{ NotImplementedJSONResponse }

func (response UpdateIssueAssignee501JSONResponse) VisitUpdateIssueAssigneeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type ListCommentsRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
	Params  ListCommentsParams
}

type ListCommentsResponseObject interface {
	VisitListCommentsResponse(w http.ResponseWriter) error
}

type ListComments200JSONResponse CommentPage

func (response ListComments200JSONResponse) VisitListCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListComments401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListComments401JSONResponse) VisitListCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListComments403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListComments403JSONResponse) VisitListCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListComments404JSONResponse struct{ NotFoundJSONResponse }

func (response ListComments404JSONResponse) VisitListCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListComments500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListComments500JSONResponse) VisitListCommentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateCommentRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
	Body    *CreateCommentJSONRequestBody
}

type CreateCommentResponseObject interface {
	VisitCreateCommentResponse(w http.ResponseWriter) error
}

type CreateComment201JSONResponse Comment

func (response CreateComment201JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateComment400JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateComment401JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateComment403JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateComment404JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateComment422JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateComment500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateComment500JSONResponse) VisitCreateCommentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueDescriptionRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
	Body    *UpdateIssueDescriptionJSONRequestBody
}

type UpdateIssueDescriptionResponseObject interface {
	VisitUpdateIssueDescriptionResponse(w http.ResponseWriter) error
}

type UpdateIssueDescription200JSONResponse Issue

func (response UpdateIssueDescription200JSONResponse) VisitUpdateIssueDescriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueDescription400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateIssueDescription400JSONResponse) VisitUpdateIssueDescriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueDescription401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateIssueDescription401JSONResponse) VisitUpdateIssueDescriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueDescription403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateIssueDescription403JSONResponse) VisitUpdateIssueDescriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueDescription404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateIssueDescription404JSONResponse) VisitUpdateIssueDescriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueDescription500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateIssueDescription500JSONResponse) VisitUpdateIssueDescriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssuePriorityRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
	Body    *UpdateIssuePriorityJSONRequestBody
}

type UpdateIssuePriorityResponseObject interface {
	VisitUpdateIssuePriorityResponse(w http.ResponseWriter) error
}

type UpdateIssuePriority200JSONResponse Issue

func (response UpdateIssuePriority200JSONResponse) VisitUpdateIssuePriorityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssuePriority400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateIssuePriority400JSONResponse) VisitUpdateIssuePriorityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssuePriority401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateIssuePriority401JSONResponse) VisitUpdateIssuePriorityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssuePriority403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateIssuePriority403JSONResponse) VisitUpdateIssuePriorityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssuePriority404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateIssuePriority404JSONResponse) VisitUpdateIssuePriorityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssuePriority500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateIssuePriority500JSONResponse) VisitUpdateIssuePriorityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueStatusRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
	Body    *UpdateIssueStatusJSONRequestBody
}

type UpdateIssueStatusResponseObject interface {
	VisitUpdateIssueStatusResponse(w http.ResponseWriter) error
}

type UpdateIssueStatus200JSONResponse Issue

func (response UpdateIssueStatus200JSONResponse) VisitUpdateIssueStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueStatus400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateIssueStatus400JSONResponse) VisitUpdateIssueStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueStatus401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateIssueStatus401JSONResponse) VisitUpdateIssueStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueStatus403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateIssueStatus403JSONResponse) VisitUpdateIssueStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueStatus404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateIssueStatus404JSONResponse) VisitUpdateIssueStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueStatus500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateIssueStatus500JSONResponse) VisitUpdateIssueStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueTitleRequestObject struct {
	IssueId IssueIdParam `json:"issueId"`
	Body    *UpdateIssueTitleJSONRequestBody
}

type UpdateIssueTitleResponseObject interface {
	VisitUpdateIssueTitleResponse(w http.ResponseWriter) error
}

type UpdateIssueTitle200JSONResponse Issue

func (response UpdateIssueTitle200JSONResponse) VisitUpdateIssueTitleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueTitle400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateIssueTitle400JSONResponse) VisitUpdateIssueTitleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueTitle401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateIssueTitle401JSONResponse) VisitUpdateIssueTitleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueTitle403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateIssueTitle403JSONResponse) VisitUpdateIssueTitleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueTitle404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateIssueTitle404JSONResponse) VisitUpdateIssueTitleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateIssueTitle500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateIssueTitle500JSONResponse) VisitUpdateIssueTitleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListProjectsRequestObject struct {
	Params ListProjectsParams
}

type ListProjectsResponseObject interface {
	VisitListProjectsResponse(w http.ResponseWriter) error
}

type ListProjects200JSONResponse ProjectPage

func (response ListProjects200JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProjects401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListProjects401JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListProjects500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListProjects500JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateProjectRequestObject struct {
	Body *CreateProjectJSONRequestBody
}

type CreateProjectResponseObject interface {
	VisitCreateProjectResponse(w http.ResponseWriter) error
}

type CreateProject201JSONResponse Project

func (response CreateProject201JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateProject400JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateProject401JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateProject422JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateProject500JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProjectRequestObject struct {
	ProjectId ProjectIdParam `json:"projectId"`
}

type DeleteProjectResponseObject interface {
	VisitDeleteProjectResponse(w http.ResponseWriter) error
}

type DeleteProject204Response struct {
}

func (response DeleteProject204Response) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProject401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteProject401JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProject403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteProject403JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProject404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteProject404JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProject500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteProject500JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetProjectRequestObject struct {
	ProjectId ProjectIdParam `json:"projectId"`
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(w http.ResponseWriter) error
}

type GetProject200JSONResponse Project

func (response GetProject200JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProject401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetProject401JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetProject403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetProject403JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetProject404JSONResponse struct{ NotFoundJSONResponse }

func (response GetProject404JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProject500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetProject500JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProjectRequestObject struct {
	ProjectId ProjectIdParam `json:"projectId"`
	Body      *UpdateProjectJSONRequestBody
}

type UpdateProjectResponseObject interface {
	VisitUpdateProjectResponse(w http.ResponseWriter) error
}

type UpdateProject200JSONResponse Project

func (response UpdateProject200JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateProject400JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateProject401JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateProject403JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateProject404JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateProject500JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetMe500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetMe500JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Delete a comment.
	// (DELETE /comments/{commentId})
	DeleteComment(ctx context.Context, request DeleteCommentRequestObject) (DeleteCommentResponseObject, error)
	// List issues with optional filters.
	// (GET /issues)
	ListIssues(ctx context.Context, request ListIssuesRequestObject) (ListIssuesResponseObject, error)
	// Create a new issue.
	// (POST /issues)
	CreateIssue(ctx context.Context, request CreateIssueRequestObject) (CreateIssueResponseObject, error)
	// Search issues by a query string.
	// (POST /issues/search)
	SearchIssues(ctx context.Context, request SearchIssuesRequestObject) (SearchIssuesResponseObject, error)
	// Delete an issue and its comments.
	// (DELETE /issues/{issueId})
	DeleteIssue(ctx context.Context, request DeleteIssueRequestObject) (DeleteIssueResponseObject, error)
	// Get a single issue by ID.
	// (GET /issues/{issueId})
	GetIssue(ctx context.Context, request GetIssueRequestObject) (GetIssueResponseObject, error)
	// Update the assignee of an issue.
	// (PUT /issues/{issueId}/assigneeId)
	UpdateIssueAssignee(ctx context.Context, request UpdateIssueAssigneeRequestObject) (UpdateIssueAssigneeResponseObject, error)
	// List comments on an issue.
	// (GET /issues/{issueId}/comments)
	ListComments(ctx context.Context, request ListCommentsRequestObject) (ListCommentsResponseObject, error)
	// Add a comment to an issue.
	// (POST /issues/{issueId}/comments)
	CreateComment(ctx context.Context, request CreateCommentRequestObject) (CreateCommentResponseObject, error)
	// Update the description of an issue.
	// (PUT /issues/{issueId}/description)
	UpdateIssueDescription(ctx context.Context, request UpdateIssueDescriptionRequestObject) (UpdateIssueDescriptionResponseObject, error)
	// Update the priority of an issue.
	// (PUT /issues/{issueId}/priority)
	UpdateIssuePriority(ctx context.Context, request UpdateIssuePriorityRequestObject) (UpdateIssuePriorityResponseObject, error)
	// Update the status of an issue.
	// (PUT /issues/{issueId}/status)
	UpdateIssueStatus(ctx context.Context, request UpdateIssueStatusRequestObject) (UpdateIssueStatusResponseObject, error)
	// Update the title of an issue.
	// (PUT /issues/{issueId}/title)
	UpdateIssueTitle(ctx context.Context, request UpdateIssueTitleRequestObject) (UpdateIssueTitleResponseObject, error)
	// List projects accessible to the authenticated user.
	// (GET /projects)
	ListProjects(ctx context.Context, request ListProjectsRequestObject) (ListProjectsResponseObject, error)
	// Create a new project.
	// (POST /projects)
	CreateProject(ctx context.Context, request CreateProjectRequestObject) (CreateProjectResponseObject, error)
	// Delete a project and all its issues.
	// (DELETE /projects/{projectId})
	DeleteProject(ctx context.Context, request DeleteProjectRequestObject) (DeleteProjectResponseObject, error)
	// Get a single project by ID.
	// (GET /projects/{projectId})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// Replace a project's mutable fields.
	// (PUT /projects/{projectId})
	UpdateProject(ctx context.Context, request UpdateProjectRequestObject) (UpdateProjectResponseObject, error)
	// Get the currently authenticated user.
	// (GET /users/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// DeleteComment operation middleware
func (sh *strictHandler) DeleteComment(ctx echo.Context, commentId CommentIdParam) error {
	var request DeleteCommentRequestObject

	request.CommentId = commentId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteComment(ctx.Request().Context(), request.(DeleteCommentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteComment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteCommentResponseObject); ok {
		return validResponse.VisitDeleteCommentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListIssues operation middleware
func (sh *strictHandler) ListIssues(ctx echo.Context, params ListIssuesParams) error {
	var request ListIssuesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListIssues(ctx.Request().Context(), request.(ListIssuesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListIssues")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListIssuesResponseObject); ok {
		return validResponse.VisitListIssuesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateIssue operation middleware
func (sh *strictHandler) CreateIssue(ctx echo.Context) error {
	var request CreateIssueRequestObject

	var body CreateIssueJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateIssue(ctx.Request().Context(), request.(CreateIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateIssue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateIssueResponseObject); ok {
		return validResponse.VisitCreateIssueResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchIssues operation middleware
func (sh *strictHandler) SearchIssues(ctx echo.Context) error {
	var request SearchIssuesRequestObject

	var body SearchIssuesJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchIssues(ctx.Request().Context(), request.(SearchIssuesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchIssues")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchIssuesResponseObject); ok {
		return validResponse.VisitSearchIssuesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteIssue operation middleware
func (sh *strictHandler) DeleteIssue(ctx echo.Context, issueId IssueIdParam) error {
	var request DeleteIssueRequestObject

	request.IssueId = issueId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteIssue(ctx.Request().Context(), request.(DeleteIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteIssue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteIssueResponseObject); ok {
		return validResponse.VisitDeleteIssueResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetIssue operation middleware
func (sh *strictHandler) GetIssue(ctx echo.Context, issueId IssueIdParam) error {
	var request GetIssueRequestObject

	request.IssueId = issueId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetIssue(ctx.Request().Context(), request.(GetIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIssue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetIssueResponseObject); ok {
		return validResponse.VisitGetIssueResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateIssueAssignee operation middleware
func (sh *strictHandler) UpdateIssueAssignee(ctx echo.Context, issueId IssueIdParam) error {
	var request UpdateIssueAssigneeRequestObject

	request.IssueId = issueId

	var body UpdateIssueAssigneeJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateIssueAssignee(ctx.Request().Context(), request.(UpdateIssueAssigneeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateIssueAssignee")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateIssueAssigneeResponseObject); ok {
		return validResponse.VisitUpdateIssueAssigneeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListComments operation middleware
func (sh *strictHandler) ListComments(ctx echo.Context, issueId IssueIdParam, params ListCommentsParams) error {
	var request ListCommentsRequestObject

	request.IssueId = issueId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListComments(ctx.Request().Context(), request.(ListCommentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListComments")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListCommentsResponseObject); ok {
		return validResponse.VisitListCommentsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateComment operation middleware
func (sh *strictHandler) CreateComment(ctx echo.Context, issueId IssueIdParam) error {
	var request CreateCommentRequestObject

	request.IssueId = issueId

	var body CreateCommentJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateComment(ctx.Request().Context(), request.(CreateCommentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateComment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateCommentResponseObject); ok {
		return validResponse.VisitCreateCommentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateIssueDescription operation middleware
func (sh *strictHandler) UpdateIssueDescription(ctx echo.Context, issueId IssueIdParam) error {
	var request UpdateIssueDescriptionRequestObject

	request.IssueId = issueId

	var body UpdateIssueDescriptionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateIssueDescription(ctx.Request().Context(), request.(UpdateIssueDescriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateIssueDescription")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateIssueDescriptionResponseObject); ok {
		return validResponse.VisitUpdateIssueDescriptionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateIssuePriority operation middleware
func (sh *strictHandler) UpdateIssuePriority(ctx echo.Context, issueId IssueIdParam) error {
	var request UpdateIssuePriorityRequestObject

	request.IssueId = issueId

	var body UpdateIssuePriorityJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateIssuePriority(ctx.Request().Context(), request.(UpdateIssuePriorityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateIssuePriority")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateIssuePriorityResponseObject); ok {
		return validResponse.VisitUpdateIssuePriorityResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateIssueStatus operation middleware
func (sh *strictHandler) UpdateIssueStatus(ctx echo.Context, issueId IssueIdParam) error {
	var request UpdateIssueStatusRequestObject

	request.IssueId = issueId

	var body UpdateIssueStatusJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateIssueStatus(ctx.Request().Context(), request.(UpdateIssueStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateIssueStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateIssueStatusResponseObject); ok {
		return validResponse.VisitUpdateIssueStatusResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateIssueTitle operation middleware
func (sh *strictHandler) UpdateIssueTitle(ctx echo.Context, issueId IssueIdParam) error {
	var request UpdateIssueTitleRequestObject

	request.IssueId = issueId

	var body UpdateIssueTitleJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateIssueTitle(ctx.Request().Context(), request.(UpdateIssueTitleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateIssueTitle")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateIssueTitleResponseObject); ok {
		return validResponse.VisitUpdateIssueTitleResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListProjects operation middleware
func (sh *strictHandler) ListProjects(ctx echo.Context, params ListProjectsParams) error {
	var request ListProjectsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjects(ctx.Request().Context(), request.(ListProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjects")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListProjectsResponseObject); ok {
		return validResponse.VisitListProjectsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateProject operation middleware
func (sh *strictHandler) CreateProject(ctx echo.Context) error {
	var request CreateProjectRequestObject

	var body CreateProjectJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProject(ctx.Request().Context(), request.(CreateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateProjectResponseObject); ok {
		return validResponse.VisitCreateProjectResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteProject operation middleware
func (sh *strictHandler) DeleteProject(ctx echo.Context, projectId ProjectIdParam) error {
	var request DeleteProjectRequestObject

	request.ProjectId = projectId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProject(ctx.Request().Context(), request.(DeleteProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteProjectResponseObject); ok {
		return validResponse.VisitDeleteProjectResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(ctx echo.Context, projectId ProjectIdParam) error {
	var request GetProjectRequestObject

	request.ProjectId = projectId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx.Request().Context(), request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		return validResponse.VisitGetProjectResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateProject operation middleware
func (sh *strictHandler) UpdateProject(ctx echo.Context, projectId ProjectIdParam) error {
	var request UpdateProjectRequestObject

	request.ProjectId = projectId

	var body UpdateProjectJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProject(ctx.Request().Context(), request.(UpdateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProject")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateProjectResponseObject); ok {
		return validResponse.VisitUpdateProjectResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx echo.Context) error {
	var request GetMeRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.Request().Context(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		return validResponse.VisitGetMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcW2/bOBb+KwR3gX1xI6ftvPgt08vAi87CaBLsQxEMaOlY5lQiVZJq4w383xckRYmy",
	"JUt2LTtp8hY7vBye8/E7NyYPOORpxhkwJfHkAWdEkBQUCPPpHU9TYGoazfTX+hvK8ARnRC3xCDOSAp7o",
	"BewgPMICvuVUQIQnSuQwwjJcQkr0xAUXKVF4gvOc6pFqlenJUgnKYjzC969i/qr4Ug+5uL2dvve/f0XT",
	"jAtlhVRLPMExVct8fhHyNIg5jxMIzNrr9XqE3+VCclEX+1sOYuXJbYZgX8i6UHqdqZQ57D4/tUMe0+k/",
	"0ZSqnYdP9Ija2SNYkDxRePJ6PMIpuadpnuLJ5Vh/oqz4VEpOmYIYhNHRTPC/IexASeYGPR49rbUkMuNM",
	"gkH77yT6DN9ykGZ6yJkCZn4kWZbQkCjKWfC35Ex/V8n8TwELPMH/CKqbFNjfyuCDEFxYm0QgQ0EzvQie",
	"4Cn7ThIaIWE3RBlZJZxEiAtUXcELvB7hj1zMaRQBG16oq1wtgSm9KkQolyBQQsKvEmUgUiol5cyINGUK",
	"BCPJNYjvIOxygwt3y+A+g1BLJs2+CPRQI9B/uPrIcxYNL8VnkDwXISDGFVroPZ0A0zRLQBMhnECMDyzK",
	"OGXKiLEChWi1uxHolpFcLbmg/zuFOH9qcLBYo5cWwCYVlihnSPGvwArJMsFDkJLME/jAFFWr4QW8hpRo",
	"YZARzork4LN2BOS7PEMggmcgFLXsYPU5jU5NUyM859GqwTuNcChA39QrVZMpIgpeKZrClmDrEaZnkN85",
	"yJNvnGfRfvpZ+77pCzYiVu69REBhEt8A/mZ35bp8rn2e1nsBqxmJYRtaVEFa/2EXyB1C1+U2RAiy0p8Z",
	"3Csb+ehFWJ4k+pI5N9txWLN3o+zmlMW2noesH8KhNKXsE7BY2+aya08zp31LE3y1bkikpDGDFmTtPvyx",
	"kVZjm07Nj3AmKBcF8+2ytdHAzA02E10YdfLbJBVRuewl8bUdqhFKVQLNobUPBD86tFPK/TxltSOlCEFb",
	"sbKvfWzQ2iW1GdUkVBkS1aUIeQSNRJ5qdxj32NGsUI1v2tsY4HHflgP81r4GPIufi3TAs6AgGo2ckDkk",
	"dZrfGrNJ6E+RJwTosSCePEcdK4CoYDHqSXQlWGra3CfesIA4QrRh6eRksUYdyJMHDCxPDddypnWVi1jH",
	"PiO8pPHSMGFE81QrjP/wFqxM6NvaW25Owq8J1wBUPOLaSuyvTPBYgNRaj+xuIWEhJAlEjUsXTqeB558l",
	"v5lA+R3PbfK0WSdq9akjzH+w87DF8a+3OWN1oppS9rm+BbSOcYEdSk92ha+BiHC5O3a31cg9swU7qWnL",
	"W6NMs+VVEec8gbRh43ieYB1nfF+RxZEi3g1R/MkdsjiubhXkwBBmK0HYkQN44limbxXmgPhgQ5BihQ4x",
	"brRrb5WiZ1Jkh7Xv9MiSnlsJ4ii+EFJCk9pw+83u23he39jq3I7iY9z5C/fS14/ogBjCXN+baw3tolAD",
	"RIC4yvWR3KePTrB///fGdYX0Sva3lZBLpTLLXJQt+BbI8OcP1zfoajZFCy6QWgIy/g8pQcKvIJBX2b0o",
	"A+CJjdHQTTHoajbFI/wdhLRrXl6ML8YmTsiAkYziCX5zMb54owNmopbmTEHRhJTBQ9mOXFvxElDGMhqU",
	"ZmdN/Pi9+d6V0jYaQa/Hb7ePVoxFdkVbZX87vmzjknLBoFaKN5PedE+quj5mxtvuGWUPZD3Cv43H3ROa",
	"ujgGMnmaEu2dCyUhggqdGpuRWNpKhFU4vtPZptc1/tK8bzUk2Ogqr/UKgQGK0X4Matten6hUUztka7um",
	"/maRZ/1FH1NftlszXte6x3CvzatHN+mhzC37NVA2PF+bbss0dY9VfdfevK4XAJ3NRndbVDA+Wneqyskb",
	"OlQzElNm+q4JlQrxhaVO+TM8cx7W0Fe1EB79oGqJuDkjSdCCJratXdFIce0NiXDZcPG9TkBxk0Gq34te",
	"w1HM0tBr2IjNNWust4BxeVxgNL4SMI6xcPcFEnrYyHvIcDLwvH39us8u273f4wHPGhIRxOCHBWAj0ipv",
	"E0iTqhpiaASfl8rKgdDXkC33QN8BMPitDww23jHU9WtFdVd7vkIEGQZHloq7lP1QdFJ7xGXVde+KyuwN",
	"eYYxGStCa8IiRJV0IVobuTYGVX+AatH0+FTcFoEiNJHPwXJ/gEIEScrixOVF8xWavm9zh3vF1LV3in5E",
	"XV27oF75+qn1RzjLGwDVUIcbiDZ3VPx6Oe8TANyKGDlPdFLn/YjvxDE8kVWtKTA4UOuI2ZFib09Ulg12",
	"5p3v3KC9E93D07kh8xD/LVKvTKTyLb8+S5vsxR0YcdYIqp8ofmwT6Y60x69PDZX4bLzrOnHqUz5m28ah",
	"K7idJ/0ZHK+PIGG6iqKquIcU78J6I4VudBkGDiu81tfwkUVDn+0luHg6VO5FCZ7yDgsU/C7mwBCfVeXV",
	"gfG92bt9AfeTBLfD5mHIrlriA+P62rUiBkZ1/QnAC6afJKYtKg9DdPm8YmBA3xTvNwfGc+0tyQucnySc",
	"DSR7obloXO+uSMzcoF+kIuE/d+xVkXBaOrwiccxygZMGkVDnanSegM6mTHlq609qfcuXxu7qf7pHnEMW",
	"Ajaek524EFA+U20wv/3VeQoBj6ytWSCmBUQ+gQQP5d8a9Oi4+QDr6rk5ezzHl1CFTk3bjSSJab25hxot",
	"97qt9daq8vEpL9VzbcA5Q2614OqcvJd33fhHGB0x5LCc3vhE+MTR4w74ufix5LOXCLIBsZ8hS0jo8c6/",
	"JEpzpd0MWlBIIrnDEehgQwb2WXIbB/05aO/fvAhvquznQgBT9j+MZIIvaAJnj+Q0O+iILbTCJauO2M2o",
	"V6vae2VtSMJ/X/3lTpOA/X8llkJykeAJDkhGg++XeH23/n8AAAD//zHOGDSCSQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
